apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: secrets
  namespace: palworld
spec:
  encryptedData:
    admin-password: AgAtr/tJOZ842PMH+jsyR1hQJj/YxPLCK28/zTBpVn0B69eSncm1Gf+JOSH5D5oFZibXN3iOlf8KKMTH9FniivR36MN3I9QUhM3KDPIoH1Q6By/ujsdXyvwv57ymejUw55jT0ih7s3fjXEH6ATKzAFOAJ3oltLbHDGIW7NfZ3JmvPT2EHukkcA+UAk6kNQ3qilK4Dpyzu+I2Og3XQqnWElkirUNxGQQXDzN88ZujTwaarv1UDcXn/0jtMkc9VNpZpw262fzUPc5PpqrXGu0E1rlOPwaQOru/EhmYKDHmNUUfel9HlC/UOi1FZn31AqIu0Cjb/RToQvbFp6l32XuVuIxp5aMqQoMK+wzLVtxxf4pasEhdyeXV9Ci5bOfdTytcR91pbwrbrT8JB74Vi0si8wGh12rXlCV7TsTuGza/rF2UazAjG/gNi9R/gfnqSL9THe5viznnL9PYyrRs6/IT7IN2MKJKlwkn3ekVF4QAsvRgvXWHLEQk+BlFkLfFFi61l+u340cnhQf3hBPVjntqmIF6C5m+nv/kssFnkc5EwwUtDOOrkCIGlqSAp/jpn918cXbA0fn0VHFNKdd787+sm+58Mw2bQ8K8VTJ73Il+xA+z0odaN5d3p/7jPBlWy26vyjs7HK8IlNTJoFtZc698PIe96eT9GvIpb1N8vgEow95IsW6SplHUPh6+KIumYhwCZnAMa24AeywYfhUXQNTaeD7DJqjmCDfslZXuIZ5NwN1lSg==
    server-password: AgC7XzhywEoW8vOyIXlSe1zNC4WBxQWGQeyDf01S4/Y2+W246v3qfp9or5OjKNnZ3z8iGBG/rV5gyo9H9STGernvb9hFKpY0B8LjejYwnza++1JXF/EGDvjAqdHp1u8/u+FNorfqIIKA3dIjwz6vuxYFQWW1vDVn0+hTM2dKtuHtg4ejDobm+6X00Dk2Oau97Z97BNRzFCneM+Z6r7Uaj4qzfiEHYl4A+a2BgSv5zj8aZsAdX4/eNjw28/r/x8/v+rij+4UUb3lxPi3S00gOzY1UzjRlyRghO2BJLcbceu1YMZioosAkKtZeesFpCuB+D7LcroKjhpdjFrC+DVCGsLP17GPW8g7F9K40vbqi+uvwdVIMSZNqOYTDJjcK5yhqAHFLcDwXN7vOI3Os9vEBu1XR+SDHgmx+QltHWlt8lYhNgUhakIz81p9Hs+62W97ImAaF0hhsRDpKL2VybKSkaV9U0g2OX+kSecO1rO8xVdx1kyj55NzGaEMURzA0AeLFCn+BQOvXeUAX57XRtT0SqaitfWYvfnKVHsG/Dg90z5YcOGozLApQxUrNMcaEI4nxha9me9R+emhRALOleB0D/sIgrMVtPBxj4pXk5bh/HifDrDSRKWZrGa38RB5cFixUioHhu8epIukisjSfJvq3W5Krb7IPqoL6PO13ilVRMrMXH0GgZ6iR7b2D/X2YqHozuVy4KPwtHtFhxuuciuD84KRseeuDqQ01fL3uO6LFfl0aEylt6WyZpfpjqIq3W1XffKPA4+210ODagM5J
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: secrets
      namespace: palworld

