apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lanjian-io
  namespace: kube-system
spec:
  secretName: lanjian-io-production-tls
  commonName: "*.lanjian.io"
  dnsNames:
    - "lanjian.io"
    - "*.lanjian.io"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
