---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app
namespace: "jdownloader"
namePrefix: "jdownloader-"
images:
  - name: "jlesage/jdownloader-2"
    newTag: "v23.06.1"
configMapGenerator:
  - name: app-config
    envs:
      - "app_config.env"
