apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: raw-secrets
  namespace: jdownloader
spec:
  encryptedData:
    gluetun-wireguard-private-key: AgBHixtEi4jmICJQ+W1S9+9ZbNxenGzIUttQQUBPMbg4VufcU/P7XRZXNPKSG0ohRxjpMtgBFWucXbLTQ34XQm7kE4+p1ielASnLgvpkaS2+CztaKgCpBcv6WN1xvO1BrsTLgFTap7WpJQwvvWH3aTzBR4gjo0Q32CK2yf/iQih11f5BF6UakUEZ4rQJMsySgGB4OA72LV8rustDoPEmFiYyjzgV197MmEFycI3zJv9a73JvRS0Fo2jKzSGuM7yxDzy0Z6c3B+GbZ8RbGdpXrwuQ+flQwcEJDIN4tz/ayc8xlDf9J9YwLfj3Ck4WHtd5qavWPJN5MlpHKmfu54KV/+hYoxueLnNyla7WmgcKU4rtIh3YlHKoJwdIfm2ZmNCwB+JDxNzGnKDCvM4Pk0qv1SKmbce8Ikhfp2t05CBW57gybs1vb5I/pcIkZKG1KR1Ud7ZAPrya3ZPaN8GEFst2VivDvZmazllfc55mkcS9tCEUqJNVp6A2h/uRKKPKH2s/2HToMDzUjk+fjGUfK4yUeOo5KLknaSNA5ygm7ZJFk7iUs9zg5hwmZI5Snv7Fwf5eNmhSM4qAIu4Kh/Bos2ylOslRFJigseioNZ3wELGa11hyPfEEPggJ3iSJYgdGCe3aD1mIfLOJjTiFMNTfQA5Ek90p/6/cb7sTVASgSslVTPTJHfuGjx1vyS2jpe3JPJB11/ZPS04yRuhxP/Rbcevo+oOqFhOMvXYa4r8BtLlm0xVfBjr7TFr8ZJiVIUb+FQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: raw-secrets
      namespace: jdownloader
