apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: "homepage"

configMapGenerator:
  - name: homepage-app-config
    envs:
      - "app_config.env"
