apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: "homepage"
namePrefix: "homepage-"

configMapGenerator:
  - name: app-config
    envs:
      - "app_config.env"
