apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml # deployment definition
  - svc.yaml # service connecting pods to cluster network
  - pvc.yaml # pvc used to store cache and attachment
  - ingress.yaml # ingress definition

configMapGenerator:
    - name: server-config
      files: 
        - server.yaml

namespace: ntfy
