apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.20.3

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: dashboard
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-http-service
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.20.4

spec:
  type: LoadBalancer
  ports:
    - targetPort: http
      name: web
      port: 80
    - targetPort: https
      name: websecure
      port: 443
  selector:
    app: traefik
