apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: dashboard
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-http-service

spec:
  type: LoadBalancer
  ports:
    - targetPort: http
      port: 80
  selector:
    app: traefik
