global:
  checkNewVersion: true
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

log:
  level: DEBUG

api:
  insecure: true

providers:
  kubernetesIngress:
    ingressClass: traefik-ingress-internal
  kubernetesCRD:
    ingressClass: traefik-internal

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http:
      tls: {}
  gitea-ssh:
    address: :2222
