---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app
namespace: "prowlarr"
namePrefix: "prowlarr-"
images:
  - name: "linuxserver/prowlarr"
    newTag: "1.23.1"
configMapGenerator:
  - name: app-config
    envs:
      - "app_config.env"
