---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app
namespace: "audiobookshelf"
namePrefix: "audiobookshelf-"
images:
  - name: "ghcr.io/advplyr/audiobookshelf"
    newTag: "2.26.0"
configMapGenerator:
  - name: app-config
    envs:
      - "app_config.env"
