- Dev:
  - github:
    - icon: github-light.png
      href: https://github.com/lanjian
  - crates.io:
    - icon: rust.png
      href: https://crates.io
  - tailscale:
    - icon: tailscale.png
      href: https://login.tailscale.com/admin

- Social:
  - reddit:
    - icon: reddit.png
      href: https://old.reddit.com
