- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: "cluster"
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
- resources:
    backend: resources
    expanded: true
    cpu: true
    memory: true
- search:
    provider: google
    focus: true
    target: _blank
- openmeteo:
    label: San Francisco
    latitude: 37.783642955200456
    longitude: -122.3989529357531
    units: metric
    cache: 5
    format:
      maximumFractionDigits: 1
- openmeteo:
    label: Richmond Hill
    latitude: 43.91494214470587
    longitude: -79.43362098413725
    units: metric
    cache: 5
    format:
      maximumFractionDigits: 1
