- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: "cluster"
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
- resources:
    backend: resources
    expanded: true
    cpu: true
    memory: true
- search:
    provider: google
    focus: true
    target: _blank
- openmeteo:
    label: SF
    latitude: 37.783642955200456
    longitude: -122.3989529357531
    units: metric
    cache: 5
    format:
      maximumFractionDigits: 1
