apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml?ref=2.7.3
  - ingress.yaml

patchesStrategicMerge:
  - argocd-cmd-params-cm.patch.yaml
  - argocd-cm.patch.yaml

namespace: argocd
