---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: "wolveix/satisfactory-server"
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - "bash"
                - "/healthcheck.sh"
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          ports:
            - containerPort: 7777
              name: game
              protocol: UDP
            - containerPort: 7777
              name: gametcp
              protocol: TCP
          envFrom:
            - configMapRef:
                name: app-config
          volumeMounts:
            - mountPath: /config
              name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-pvc
