apiVersion: v1
kind: Service
metadata:
  name: svc
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.50.8
spec:
  type: LoadBalancer
  ports:
    - name: game
      targetPort: game
      port: 7777
      protocol: UDP
    - name: gametcp
      targetPort: gametcp
      port: 7777
      protocol: TCP
