apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lanjian-io
  namespace: default
spec:
  secretName: lanjian-io-staging-tls
  commonName: "*.lanjian.io"
  dnsNames:
    - "lanjian.io"
    - "*.lanjian.io"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
