---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: app
          image: "ghcr.io/seerr-team/seerr:latest"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: "app-config"
          ports:
            - name: http
              containerPort: 5055
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /app/config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
