---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app
namespace: "plex"
namePrefix: "plex-"
images:
  - name: "linuxserver/plex"
    newTag: "1.32.5"
configMapGenerator:
  - name: app-config
    envs:
      - "app_config.env"
