apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cert-manager
  name: cert-manager
spec:
  template:
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 1.1.1.1
          - 9.9.9.9
