---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../../components/app"
namespace: "satisfactory"
namePrefix: "satisfactory-"
images:
  - name: "wolveix/satisfactory-server"
    newTag: "latest"
configMapGenerator:
  - name: app-config
    envs:
      - "app-config.env"
